### ISSUE TITLE
Fullscreen not working on iPad

### ISSUE THREAD

**Issue by brylie** [adilyalcin/Keshif#110]
On an iPad, with both Chrome and Safari browsers, the fullscreen button does not work. When clicking the fullscreen button, the arrows turn reddish orange, but the pivot table keeps its previous dimensions.

Steps to reproduce on an iPad tablet

1. Visit the project website
2. On the demo, click the fullscreen button

**Comment by adilyalcin** [comment]
iOS Safari does not support FullScreen API :: http://caniuse.com/#feat=fullscreen
