### ISSUE TITLE
Drag handles on filters are difficult or impossible to use on tablet

### ISSUE THREAD

**Issue by brylie** [adilyalcin/Keshif#111]
On a tablet device, the drag handles below graph filters are difficult or impossible to use. When touching a drag handle, it might turn red, but it does not seem possible to drag the slider.

Steps to reproduce on an iPad,

1. Visit the project website
2. On the demo, touch a filter slider
3. Attempt to drag the slider

**Comment by brylie** [comment]
This issue could be resolved by using the [jQuery Mobile range slider](http://demos.jquerymobile.com/1.4.5/rangeslider/)

**Comment by adilyalcin** [comment]
Closing this because there is no current plan to improve on the tablet / touch interaction.
