### ISSUE TITLE
Filter slider handles are quite small for touch interaction

### ISSUE THREAD

**Issue by brylie** [adilyalcin/Keshif#112]
when attempting to interact with filter sliders from a tablet, it is difficult to accurately touch the slider due to their small size. Please consider improving the usability of filter sliders for touch enabled devices such as tablets.

**Comment by adilyalcin** [comment]
Hi @brylie ,

Currently, keshif is not designed for the best experience with touch screens or small displays. It focuses on offering a smooth mouse-based interaction on desktop/laptop devices.

Thank you for your feedback and interest, and I hope you can continue finding use cases for Keshif!

Adil

**Comment by brylie** [comment]
@adilyalcin thanks for your quick response. 

We are considering using Keshif as a dashboard for nurses and administrators in a healthcare facility. The healthcare workers have ready access to tablet devices, and may want to interact with our information dashboard via those, and other, touch-enabled devices. This is an emerging demographic, so might be of value to put touch support and usability testing on the Keshif roadmap.

**Comment by brylie** [comment]
This, and other touch related usability issues might be resolved by using [jQuery Mobile](http://demos.jquerymobile.com/1.4.5). E.g.

- touch enabled [range slider](http://demos.jquerymobile.com/1.4.5/rangeslider/)

**Comment by adilyalcin** [comment]
Closing this because there is no current plan to improve on the tablet / touch interaction.
