### ISSUE TITLE
Flag demo example not loading

### ISSUE THREAD

**Issue by romsson** [adilyalcin/Keshif#119]
http://keshif.me/demo/flags

<img width="1230" alt="screen shot 2016-03-29 at 1 46 19 pm" src="https://cloud.githubusercontent.com/assets/586236/14106896/ac322aec-f5b4-11e5-836a-aea971ee50bc.png">

Mac Yosemite / Chrome Version 49.0.2623.87 (64-bit)

**Comment by adilyalcin** [comment]
Thanks @romsson ! Fixed now.
