### ISSUE TITLE
CSV file not accepted as local input

### ISSUE THREAD

**Issue by wolfego** [adilyalcin/Keshif#149]
Tried on both Firefox and Chrome.  Worked for me 2 days ago but now not accepted as valid file type.  Used Excel to save as .csv in both standard and Mac format, neither worked.

**Comment by adilyalcin** [comment]
Hi @wolfego, Sorry about the issue. It is interesting that it was working before and now it is not.

To help me reproduce the issue:
- Are you loading your data through GUI or JS configuration?
- Did you try some other CSV file, or a simplified version of the same file? (Can you share the first few lines of this file?)
- Are you hosting Keshif yourself, as a localhost or some other server?

I don't exactly have much clues as to what might have happened, so I hope some specific information may help us figure this out.
