### ISSUE TITLE
calendar heatmaps and D3 module integration in general

### ISSUE THREAD

**Issue by magneticnorth** [adilyalcin/Keshif#155]
Appreciate this very powerful software.  How would one get calendar heatmaps in keshif?  In general, is there a recommended way to cleanly integrate a D3 module found on the side of the road somewhere? Stephen

**Comment by adilyalcin** [comment]
Hi Stephen,

Keshif is not aimed to be a modular programming interface. Such extensions are still possible, and can be implemented given the motivations of a specific project, and generalized properly to become a part of the "whole solution". Overall, I want to make sure that Keshif works seamlessly for its main use cases. That means that the way multiple components work together also should be seamlessly implemented. Achieving "seamless" modularity is even a greater challenge. I can say Keshif will not become a project where arbitrary d3 modules can be integrated with minimal effort. Keshif will not make it "easy" to integrate ineffective or poorly executed charts and designs.

That said, I think one simple approach to think about calendar is to think of each dimension separately: One dimension can be day of week, or the other can be time of day, for example. You get the overview of both components first, and can query and filter to see the relations across, and use existing visualization modalities to make the insights richer. That of course does not reveal all the combinations as a matrix-like view/heatmap. But, that's the first step I'd take in such a scenario, and it would provide a working interface to this data.

If you need an integrated solution for a specific "calendar" view and have resources to support the development, please let me know in person.

Adil

**Comment by magneticnorth** [comment]
Adil, thank you for explaining your approach.   Also I will try again with the case to find
some funding for this work. Companies are funny, and I’m not in an executive position 
any more so I don’t know about their budget situation.  I do hope you find some interesting
things to do and I would be more than happy to write a recommendation if it doesn’t 
have to be too lengthy.
Stephen
