### ISSUE TITLE
is it possible to overlay charts?

### ISSUE THREAD

**Issue by magneticnorth** [adilyalcin/Keshif#157]
Greetings. Is it possible to overlay two charts, like "temperature" and "errors"?  I realize Keshif is not meant to be an alll-purpose data visualization system, so I suspect the answer is no, just checking.

**Comment by adilyalcin** [comment]
Hi! Keshif would present temperature and errors as two separate summaries. It does not currently support a chart that would show (temperature vs. errors) like a heatmap, etc. Keshif may have a way to show bi-variate summaries in the future! It does not also support overlaying two metrics on a single chart, such as showing temperature and errors on a shared time axis with two different axis and line encodings. But, this inconsistent design would potentially be a crime against its will:) I think that the first use case is very useful though. It's been on my mind for a while, but a smooth and generic design is tricky to get right.
