### ISSUE TITLE
Keshif app for desktop

### ISSUE THREAD

**Issue by adilyalcin** [adilyalcin/Keshif#159]
Is it the future?

Porting the website to a desktop app based on chromium and node.js would allow for flexible database access and a more integrated, standalone solution.

http://electron.atom.io/
http://nwjs.io/

**Comment by hydrosquall** [comment]
Rishi Singh of Tiingo seems to have had good luck with porting his webapp to Windows 10 native in just a [few minutes](https://developer.microsoft.com/en-us/windows/projects/stories/tiingo-shows-how-to-use-windows-app-studio-to-create-a-hosted-web-app). Haven't tried it myself but planning to do so soon.

**Comment by adilyalcin** [comment]
Thanks @hydrosquall ! I will keep this in mind if I decide to take the embedded desktop-app way.

**Comment by adilyalcin** [comment]
I also found  https://github.com/MacGapProject/MacGap1 that would be nice for this packaging a mac app. (Slack Mac App uses this apparently)

(Note: I'm just adding notes here. The issue is *not* under active development roadmap. )
