### ISSUE TITLE
Multi-Valued Categorical Attributes and Google Sheet

### ISSUE THREAD

**Issue by aborruso** [adilyalcin/Keshif#177]
Hi,
I have a single column with categorical attributes, I use these as tags.

When I add this column to the browser, the tags are not splitted: in example in my tags column I have the value "tech,iot,2017" and in the browser it remains "tech,iot,2017" and I do not 3 categories, "tech", "iot" and "2017".

I have used also `+` as separator. My data source is a gdrive sheet, and I'm using "Import your data" [page](http://www.keshif.me/demo/YourData).

Thank you

**Comment by adilyalcin** [comment]
Hi,

I think you are very close to the working solution! Did you try using "," character as a splitter?

You can split a categorical attribute using the UI as well in authoring mode. Just an example below. Enter "," character when it asks for text.
![image](https://cloud.githubusercontent.com/assets/2327953/22377161/d2476ac6-e47e-11e6-9af5-010bf66d980f.png)

Let me know if this works.

Adil

**Comment by aborruso** [comment]
hi @adilyalcin it works, thank you very much
