### ISSUE TITLE
keshif.js loses styling when in offline mode

### ISSUE THREAD

**Issue by mdudel** [adilyalcin/Keshif#178]
When using keshif without an internet connection the various online resources do not load. Is there an offline version of keshif.

**Comment by adilyalcin** [comment]
You can run the open-source version on your own computer without an internet connection. If you connect to an online data souce (such as google sheet or a cloud file), or if you import images and custom styles from other websites, you'll still need to be connected online.

If you have a professional use case and want to get an updated version for offline use, and for more support, we'll be happy to hear from you at info @ keshif.me.

Thanks for your input & interest,
