### ISSUE TITLE
Lock icon is outside the view when the bar width is full

### ISSUE THREAD

**Issue by adilyalcin** [adilyalcin/Keshif#81]
The lock is partially visible (or invisible, depending on the browser/IS) when the selected bar is full length.

Maybe the lock should be placed on top of the bar when the bar is (almost) full. Some white text-shadow can be used to separate it from the black lines. I would rather not reserve extra white space for the lock, which is not something used very often, so the lock needs to go within the bars.

Note: This would also affect the position of the aggregate tooltip.

![screen shot 2015-04-11 at 8 48 14 pm](https://cloud.githubusercontent.com/assets/2327953/7103932/250585e8-e08c-11e4-8081-cbe3b82544d8.png)

![screen shot 2015-04-11 at 8 48 30 pm](https://cloud.githubusercontent.com/assets/2327953/7103933/298458f6-e08c-11e4-9cb7-f55d03ea5a3a.png)

**Comment by fernoftheandes** [comment]
Hi Adil,

Maybe that is what you are saying already...not sure...what about a WHITE lock icon INSIDE the bar, right-justified?

**Comment by adilyalcin** [comment]
That's a great idea Nivaldo. Changing the color to white might work since the lock will be fully within the bars and bars have a dark shade. Thanks:)

**Comment by adilyalcin** [comment]
Done.

![image](https://cloud.githubusercontent.com/assets/2327953/7717678/4467c928-fe73-11e4-8433-75667d290b50.png)
