### ISSUE TITLE
One-button to expand categorical summary within a panel

### ISSUE THREAD

**Issue by adilyalcin** [adilyalcin/Keshif#86]
When there are multiple summaries in a panel, and a couple of them have long lists, one use-case is to expand one of the facets fully, and close the others.

Currently, to do this, all other facets need to be manually closed, and one of them need to be expanded. This can be tedious, animated positions of summaries are further complicating the use.

So, add a single button to a summaries: probably only for categorical, when it has more items to be shown, and there is potential screen-space saving by collapsing other summaries.

**Comment by fernoftheandes** [comment]
:thumbsup: for thinking of ways  to optimize screen real-state

**Comment by adilyalcin** [comment]
Done:)
