### ISSUE TITLE
How to check if the facet is searched?

### ISSUE THREAD

**Issue by isharsha** [adilyalcin/Keshif#90]
I'm trying to have a default ranking for my itemDisplay as well as a more specific ranking based on whether or not there is a search that is called. Is there anyway to check?

**Comment by adilyalcin** [comment]
Hi @isharsha , can you explain in more detail how you want to sort the individual records in your data?

**Comment by isharsha** [comment]
Hi @adilyalcin , I am making a view with the following JSON structure:

{
personName: "some name",
background: "some info",
totalScore: 393,
games: [
{
name: "diablo",
score: 102
}
,...
]
}

I would to view the records based on just the totalScore, and then when a game is selected, see ranking based on the score for an individual game.

**Comment by adilyalcin** [comment]
So, if i understand this correctly:

- You have a dataset of people, and each person (player) can play multiple games, and earn a score with each game.
- You probably want to show the list of games [Diablo, Fallout, World of Warcraft, ...] as a summary (categories), which will show the number of people playing that game by default.

- You want to sort each player on the list by their score. By default, you want to use "totalScore" as your sorting option (sortingOpts parameter in itemDisplay configuration).

- You also want to enable sorting by game type. To enable this, you can add new options into SortingOpts parameter. For example, you can define the following:

sortingOpts: [
    "totalScore",  // The default property to sort by
     {title: 'Diablo Score', value: function(){ return this.games[0].score; } // The game-based property
]

Now, it is possible to change sorting option. Yet, this would not automatically change the sorting option when a game name is chosen in the summary (not on the sort-options). This is not a supported behavior right now.

I hope this helps.
