### ISSUE TITLE
Waiting indefinitely when loading local .csv files makes 

### ISSUE THREAD

**Issue by i3visio** [adilyalcin/Keshif#92]
I have just tried a fresh installation of the explorer:
```
git clone https://github.com/adilyalcin/Keshif/
firefox file:///home/my_user/Development/Keshif/demo/women_in_film.html
```
This demo is using a text-file approach as follows and works smoothly with the following source:
```
        source: {
            url: "http://women-in-film.silk.co/",
            dirPath: 'https://ca480fa8cd553f048c65766cc0d0f07f93f6fe2f.googledrive.com/host/0By6LdDWgaqgNfmpDajZMdHMtU3FWTEkzZW9LTndWdFg0Qk9MNzd0ZW9mcjA4aUJlV0p1Zk0/',
            fileType: 'csv',
            sheets: "women_in_film"
        },
```
However, when changed to the locally downloaded version of https://ca480fa8cd553f048c65766cc0d0f07f93f6fe2f.googledrive.com/host/0By6LdDWgaqgNfmpDajZMdHMtU3FWTEkzZW9LTndWdFg0Qk9MNzd0ZW9mcjA4aUJlV0p1Zk0/women_in_film.csv (stored under /home/my_user/Development/Keshif/demo/data/) this does not work:
```
        source: {
            url: "http://women-in-film.silk.co/",
            dirPath: 'file:///home/my_user/Development/Keshif/demo/data/',
            fileType: 'csv',
            sheets: "women_in_film"
        }, 
```
According to the docs, this would create a valid URL: file:///home/my_user/Development/Keshif/demo/data/women_in_film.csv which in fact is accessible in the browser. However, the browser cannot be loaded and gets stuck in the following window:

![keshif](https://cloud.githubusercontent.com/assets/8018610/9620302/103b9744-5119-11e5-9324-08aa8ab5aff5.png)

I have already tested the following approaches with the same results:
```
            dirPath: '/home/my_user/Development/Keshif/demo/data/',
            dirPath: '/home/my_user/Development/Keshif/demo/data',
            dirPath: 'data/',
            dirPath: 'data',
            dirPath: './data/',
            dirPath: './data',
```

Paths are correct and all users have at least read permissions on the files. This is also happening in other demo files. I'm pretty sure that I am missing something. Note that the csv/tsv library is stored as stated in the Tutorial.
```
        <script type="text/javascript" src="../js/papaparse.min.js" charset="utf-8"></script>
```
Am I missing something?

**Comment by adilyalcin** [comment]
To access local files, you need to run keshif on a local server (commonly called localhost). If you open html files directly in the browser, they will not be able to load the data files. If you open the html files with a url like http://localhost/keshif/demo/_demoname_ , the web pages should be able to access the files and create the visualization. 

If this is the problem, your browser debug console should also be displaying some error logs now as it cannot read files on disk. This is because of security features in browser to block websites from accessing your files on disk. Wouldn't it be a security nightmare if this was allowed haha. It makes development a little more effortful though.

**Comment by i3visio** [comment]
Oh. That makes sense ;). Anyway, what do you think about bundling a sort of html, javascript interpreter (i'm thinking about nodewebkit or so) to have the chance of displaying the information directly. The idea is that the users of the visualization suite (even non-technical ones) would be able to render their local data without further configuration. Would you feel that this could be a solution to our problem? We're still trying to think about different ways of integrating the suite, because it looks great. ;) Thanks for the efforts man!
